### ISSUE TITLE
Assignment Recruitment pre process function: check if the paper id is still an active submissions

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1147]
Otherwise send an error so the user that is accepting the invitation knows that submission is not active anymore.

**Comment by purujitgoyal** [comment]
Could you specify which pre-process function file?

**Comment by melisabok** [comment]
This pre-process function runs before posting a response note: https://github.com/openreview/openreview-py/blob/master/openreview/conference/templates/assignment_pre_process.py

You can reproduce this issue doing the following thing:

- invite a reviewer to review a paper 
- desk reject or withdraw the paper
- the reviewer clicks on the link that received my email. 
- the reviewer should see an error message saying: "the submission in not under submission anymore".

Please add this test to test_arr_venue.py file. There are already a few invite assignments implemented in the test.

**Comment by purujitgoyal** [comment]
Following the steps @melisabok, you mentioned, I was able to get the process function to fail with the new exception `the submission is not under submission anymore`, but I had to add an exception in [simple_paper_recruitment_process.py](https://github.com/openreview/openreview-py/blob/master/openreview/conference/templates/simple_paper_recruitment_process.py) rather than [assignment_pre_process.py](https://github.com/openreview/openreview-py/blob/master/openreview/conference/templates/assignment_pre_process.py).

Second, I am still able to accept the invite assignment through the link, i.e. it doesn't show me the error in UI but the process function does fail.

**Comment by melisabok** [comment]
the pre_process function runs before the note is saved in the database, if this function fails then when you follow the link you will see an error in the UI.

the process function runs after the note is saved in the database, if this function fails then the user doesn't get notified in the UI because this function runs asynchronously, only us receive an email with the error and it is too late to notify the user. 

you need to check if the submission is still under submission in the pre_process function and your tests must do a request_page and expect to see an error message.

**Comment by purujitgoyal** [comment]
Yes, I did this initially but that didn't work. 

Right now, I tried to raise an exception no matter what in [assignment_pre_process.py](https://github.com/openreview/openreview-py/blob/master/openreview/conference/templates/assignment_pre_process.py) but I was still able to go through the link without any error on UI with the process function still failing.
