### ISSUE TITLE
Comment Stage Readers and Participants Should be Separate

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1325]
When running the Comment Stage, PCs currently select "Participants". The participants are those who can post a comment and who appear as options in the readers dropdown on the comment form. Sometimes the PCs may want the groups who can post comments to be different than the groups who can read comments. There should be the option to select Participants and a separate option for selecting readers.

**Comment by melisabok** [comment]
I agree, we should have two different fields here: one to select the invitee/signatures and another one to select the readers. 

I would call the fields "Participants" and "Readers"? There is one restriction here, the participants must always be a subset of the readers because if they participate in the comments they must read them.

**Comment by purujitgoyal** [comment]
@melisabok "Participants" here are never actually used to determine the users who can post a comment, only to determine readers. See [here](https://github.com/openreview/openreview-py/blob/a0095a4ec0e887ea89f59ef55a910c353fdd5773/openreview/conference/builder.py#L2466), only the authors if selected in participants update the invitees to add the authors.

**Comment by melisabok** [comment]
So the "Participants" feature wasn't fully implemented :(

Could you fix it?

I think we haven't found the issue because most of the cases the Comment Stage is configured with or without authors.
