### ISSUE TITLE
Validation: add validation for curly braces in Recruitment

### ISSUE THREAD

**Issue by racheljsmart** [openreview/openreview-py#1594]
PCs often leave out the double curly braces when using Recruitment or sending Recruitment Reminders. Add validation for this.

**Comment by celestemartinez** [comment]
I wonder if this is something we need to validate? 
We are catching this in the error: https://openreview.net/forum?id=XmoAOBSvaZ&noteId=WbABCsfpU1g and we have a test for this: https://github.com/openreview/openreview-py/blob/a91c8af1c71ae55dc4646057260f00bdb116d698/tests/test_venue_request.py#L555

cc @melisabok @racheljsmart

**Comment by melisabok** [comment]
What about adding a pre process function? adding Emilia so she can take a look.

**Comment by melisabok** [comment]
Emilia and I realized that we don't have the `Key error` anymore because we are using find and replace to replace the tokens:

https://github.com/openreview/openreview-py/blob/master/openreview/tools.py#L1284

I still suggest creating a pre-process function to validate that the words that are wrapped between `{{}}` must be supported by us, this is the list of tokens supported, there are different tokens per field:


invitation_email_subject:

- invitee_role

invitation_email_content:

- fullname
- contact_info
- invitation_url (I would ignore accept_url and decline_url because this is legacy recruitment code)
- invitee_role

accepted_email_template:

- fullname
- reviewer_name
