### ISSUE TITLE
Request form: Improve wording of Submission Deadline Author Reorder

### ISSUE THREAD

**Issue by enrubio** [openreview/openreview-py#2159]
PCs are still getting confused about how to interpret this field. One way to make it more clear is if we change the options to be something like: "Allow author reorder only", "Allow add/remove authors", and "Don't allow changes".

**Comment by celestemartinez** [comment]
The current options are as follows, I am not sure your suggestion makes them any more clear?

-  'Allow addition and removal of authors',
-  'Allow reorder of existing authors only',
-  'Do not allow any changes to author lists'

I am hesitant to make this change and changing the values since some venues will already have these values. What if we change the description:

`'description': 'Choose how authors may edit the author list. You can allow authors to 1)add/remove authors, 2)reorder existing authors only or 3)make no changes to the author list.'`

What do you think? @melisabok @enrubio

**Comment by melisabok** [comment]
ok, let's change the description.

**Comment by enrubio** [comment]
Ooh I see. I made this issue after changing author reorder for Neurips and their request form still has the old options: `Yes / No / No changes`

I forgot we already changed this. I think the description & options we have now are self-explanatory and straightforward. I'm ok with closing the issue.
