### ISSUE TITLE
Regex search for invitations

### ISSUE THREAD

**Issue by carschno** [openreview/openreview-py#630]
Not sure if this is a bug or a user mistake, but I don't seem to be able to apply the `regex` parameter to get invitations properly. For instance, I would like to get all submissions for [ICLR conferences](https://openreview.net/group?id=ICLR.cc), so I try this regex: 

`ICLR.cc.*[Ss]ubmission`

This returns the invitations relevant to the conferences and workshops from 2018, 2019 and 2020, but the previous ones (e.g. `ICLR.cc/2017/conference/-/submission`). I've tried a variety of regexes, but I don't seem to find a regex to get all the ICLR conference submissions. `.*[Ssubmissions]` (as mentioned in #136) seems to work, but that is hardly a useful filter.

**Comment by mohituniyal** [comment]
Hi @carschno , thanks for informing us about this. It is not a bug. Since, some of these venues that you are looking for are pretty old, their respective invitations might have expired.

Try using this and this should get you all the ICLR submission invitations:
`all_iclr_invitations = client.get_invitations(regex='ICLR.cc/20.*/[Ss]ubmission', expired=True)`

Let us know how it goes for you.

**Comment by carschno** [comment]
@mohituniyal Thanks for the pointer, the `expired` flag was indeed missing.
