### ISSUE TITLE
Builder: create withdraw and desk reject invitations for all the venues

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#650]
I think the place to put these calls is when we call `create_blind_submissions`, thoughts?

**Comment by mohituniyal** [comment]
Yes, right after the line https://github.com/openreview/openreview-scripts/blob/ed13c606f5c626f1fa1505a2c2ded5e9e244286a/venues/OpenReview.net/Support/revisionProcess.py#L19 would be a good place. This would mean that the change goes in openreview-scripts repo.
@melisabok is this what you have in mind or do you want the `create_blind_submissions` method to call `create_withdraw_invitations` and `create_desk_reject_invitations`?

**Comment by melisabok** [comment]
I think we should do it inside of `create_blind_submissions`, enable this feature by default for all the venues. 

I'm not sure if the withdraw and desk reject invitation support venues with different configurations, like `single blind` , `public` or `private`.

**Comment by mohituniyal** [comment]
@melisabok The withdraw and desk reject invitations do support double, single blind and also support both public and private submission type venues. Methods to enable each of these invitations take these 2 inputs `reveal_authors`, `reveal_submission` and that should allow it to work for all types of venue configurations.

Re: calling these 2 invitation setup functions inside create_blind_submissions, that would only enable these for double blind venues, right? If we want these 2 enabled for all venues, we may have to call them somewhere else.

**Comment by melisabok** [comment]
You are right, but we have a dependency of  groups. They need to be created before we open these invitation. When the venue is single blind we should call to create paper groups instead of create_blind_submissions. 

May be we should have a everything in a single function, close_submissions? that calls either create blind submissions or create paper groups and then create the desk reject and withdraw invitations.

Close submissions should be called from all the process function.

**Comment by mohituniyal** [comment]
> You are right, but we have a dependency of groups. They need to be created before we open these invitation. When the venue is single blind we should call to create paper groups instead of create_blind_submissions.
> 
> May be we should have a everything in a single function, close_submissions? that calls either create blind submissions or create paper groups and then create the desk reject and withdraw invitations.
> 
> Close submissions should be called from all the process function.

@melisabok `close_submissions` bears the primary responsibility of closing the submission invitation. 
Now, if I place the logic for creating blind submissions and paper groups inside `close_submissions`, I still can not call `close_submissions` method from the `stage` button processes on the request forum. This is because if a PC submits one of `Stage` forms, that would then close the submissions regardless of whether it should be closed at that point, and this can be problematic.

I have added a new method `setup_venue_papers` which carries out the following tasks if `submission_stage.due_date` is None or if `submission_stage.due_date` is in the past:
1. Check if `submission_stage.double_blind` is True:
1.1 If True -> create double blind submissions (which also calls to create paper groups)
1.2 Else -> create paper groups
2. Create `withdraw` and `desk_reject` invitations for submissions using `reveal_authors = False` if venue is double blind AND `reveal_submissions = False`.

**Comment by mohituniyal** [comment]
This is fixed with #701 .
The new method `setup_post_submission_stage` creates paper withdraw and desk reject invitations for each venue based on the config params that are provided in the request form and are saved in the conference data model as a member of the submission stage.
