### ISSUE TITLE
Builder: open_revise_submissions() error

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#693]
When trying to extend deadline for revisions, got following error:

> Invalid Array Value
The value type array in the array invitation.invitees is invalid. Expected value type: string

Working on KAIST workshop https://openreview.net/forum?id=ekx5JOGxp

**Comment by mohituniyal** [comment]
@celestemartinez It seems the `authorids` field in KAIST workshop is a list of lists:
<img width="664" alt="Screen Shot 2020-06-24 at 3 28 15 PM" src="https://user-images.githubusercontent.com/13500158/85535586-f4807980-b62f-11ea-9ac5-09fe5dcca452.png">

We do a list of strings for `authorids` like so:
<img width="780" alt="Screen Shot 2020-06-24 at 3 29 16 PM" src="https://user-images.githubusercontent.com/13500158/85535659-0530ef80-b630-11ea-8049-fb2b775a1bca.png">

Was this intentional for KAIST? If not, I think fixing this should fix the revision issue as well. 

I am not sure what other side effects you might have faced with this workshop because of `authorids` being a list of lists.

**Comment by melisabok** [comment]
@mohituniyal I fixed the data a few days ago, do you still see the authorids as an array of arrays?

**Comment by mohituniyal** [comment]
@melisabok You are right, the issue was just on my local db which is a bit outdated now. I'll retry on the latest db dump. I don't expect to see the issue with it.

**Comment by melisabok** [comment]
Ok, i'm closing this issue.
