### ISSUE TITLE
AnonReviewers group: add the Authors group as nonreaders

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#729]
It seems we are not hiding the identity of the reviewers of the papers where the PC is an author. 

Issue reported by: https://openreview.net/group?id=ijcai.org/IJCAI-PRICAI/2020/Workshop/XAI

**Comment by mohituniyal** [comment]
@melisabok The Authors are added as non-readers for the AnonReviewer groups.
<img width="1071" alt="Screen Shot 2020-08-05 at 3 15 59 PM" src="https://user-images.githubusercontent.com/13500158/89398875-4c31fa80-d72f-11ea-9873-4548aa21881d.png">

And the PC User is not able to access the group directly because of being an author of this paper:
<img width="1147" alt="Screen Shot 2020-08-05 at 3 13 43 PM" src="https://user-images.githubusercontent.com/13500158/89398885-505e1800-d72f-11ea-9c13-26a128e1dcd2.png">

I think the issue is that on the forum page the `get /notes` api call to get the forum replies is getting the `tauthor` for all the reviews when the PC is logged in.
<img width="1280" alt="Screen Shot 2020-08-05 at 3 20 09 PM" src="https://user-images.githubusercontent.com/13500158/89399570-4c7ec580-d730-11ea-8c34-935ecccb6098.png">

I found that when I log in as a Reviewer for this paper, I can only see the tauthor for the review that the logged-in reviewer had posted. For the PC user on the other hand, tauthor is being returned for all the reviews.

It does not seem like an openreview-py issue.

**Comment by melisabok** [comment]
Thanks Mohit for checking this. You are right, the bug is in the backend when it checks if the logged user can see the tauthor of the note. There is an OR condition, where if the user is writer of the note then it can see the identity, I think this is not correct. What do you think?

**Comment by melisabok** [comment]
Here is the code: https://github.com/openreview/openreview/blob/master/repositories/notes.js#L520

if the user is ( writer OR author OR reader_of_the_signature_group OR super_user) then the identity is revealed.

**Comment by mohituniyal** [comment]
> Thanks Mohit for checking this. You are right, the bug is in the backend when it checks if the logged user can see the tauthor of the note. There is an OR condition, where if the user is writer of the note then it can see the identity, I think this is not correct. What do you think?

You are right. The PCs need not be writers for official reviews.

**Comment by mohituniyal** [comment]
@melisabok can we close this issue since it was fixed at https://github.com/openreview/openreview/pull/2165 ?

**Comment by melisabok** [comment]
Yes!
