### ISSUE TITLE
Post submission stage: don't update the submissions if the readers are already set

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#855]
For single-blind venues, every time the post submission stage is run the submissions are updated setting a modification date. Similar to what we do in double-blind venues, we should check if the submission already has the readers for the post submission stage and don't update the note.

**Comment by melisabok** [comment]
I think this issue is fixed, right?

**Comment by celestemartinez** [comment]
Is this for `setup_first_deadline()` or `setup_final_deadline()`? 

`setup_first_deadline()` does not change the readers unless we pass `submission_readers`, which is never done through the request form.
`setup_final_deadline() `does change the readers every time I believe, since we are not checking the readers anywhere: https://github.com/openreview/openreview-py/blob/1c7b9a8c7072e68fde7184fe981f204e584ec55a/openreview/conference/builder.py#L846
but the tmdate is not being changed anymore and emails are not being sent since we remove the submission process function.
Should I still add a check so we don't repost notes everytime?

**Comment by melisabok** [comment]
I would try to avoid the update in case there is no change needed. In the future, these steps are going to be run by the PCs  and modification dates are going to be updated.
